[package]
edition = "2021"
name = "app-load-path"
version = "4.0.0-preview1"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-i18n = { path = "../.." }
